### ISSUE TITLE
Complete basic example

### ISSUE THREAD

**Issue by elmarti** [elmarti/blaze-video-chat#1]
Currently the only example for `meteor-video-chat` is written using React, which makes it difficult for some users to develop with. 

Already complete for this project: 

- Base CSS - using bootstrap 3 + a few customisations
- User status loading - users can sign up and their online status will be shown
- First step of call flow, users can trigger a call, but no callback handling has been implemented. 

CC: @sir007

**Comment by elmarti** [comment]
@sir007 basic example complete, example app here https://blazevideochat.herokuapp.com/

**Comment by sir007** [comment]
Thank you elmarti for that great job.
I'm curently trying to use blaze-video-chat. 
I get an error:
"Exception from Tracker recompute function:
meteor.js:992:11
TypeError: Meteor.VideoCallServices.init is not a function
dashboard.js/<@http://localhost:3000/app/app.js?hash=e495e61a6e6b8a20de9d975bb795d0457d1315c5:160:5
fireCallbacks/<@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3398:9
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12
fireCallbacks@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3394:3
Template.prototype.constructView/<@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3474:5
fireCallbacks@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2014:19
Tracker.nonreactive@http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:640:12
Blaze._fireCallbacks/<@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2011:5
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271:12
Blaze._fireCallbacks@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2010:3
Blaze._createView@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2028:3
Blaze._materializeView@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2073:3
materializeDOMInner@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1532:9
Blaze._materializeDOM@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1474:3
Blaze._materializeDOM@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1483:7
doMaterialize@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2092:32
Tracker.nonreactive@http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:640:12
doRender@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2090:9
viewAutorun/</<@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1934:18
Template._withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:3744:12
viewAutorun/<@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1932:14
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:2271:12
viewAutorun@http://localhost:3000/packages/blaze.js?hash=f33d3dfed63a491d24e3aa07ad66c24b5fe8c761:1931:12
Tracker.Computation.prototype._compute@http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:339:5
Tracker.Computation.prototype._recompute@http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:358:9
Tracker._runFlush@http://localhost:3000/packages/tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:532:9
onGlobalMessage@http://localhost:3000/packages/meteor.js?hash=cbcc712d51de4298c275e8dcf25c66c29914f19a:448:11

Do you have any idea?

**Comment by elmarti** [comment]
Interesting, having a look now

**Comment by elmarti** [comment]
But yes, thank you for finally giving me the motivation to do this!

**Comment by elmarti** [comment]
Which browser are you using? 
When is it ocurring? before, or after login and after clicking something?

**Comment by sir007** [comment]
I'm using firefox 57 and chrome 63.
It is occurring after login on the 2 browsers. Then impossible to display users.

**Comment by elmarti** [comment]
I can't say what the issue is, as the application seems to be working on Ubuntu and WIndows and across Chrome, Firefox and Edge. Perhaps an issue with your install? I have pushed some updates since last week if you would like to try them.

**Comment by sir007** [comment]
Thanks elmarti
The problem was my install. I was using elmarti-video-chat 1.2.0 
I tried with 2.1.0 on a new meteor install. It is OK.

I have the following error when the call is made with firefox 57:


error 
TypeError
columnNumber: 9
fileName: "http://localhost:3000/packages/elmarti_video-chat.js?hash=b47cfc90884f41cd3c7e4c69d06caa1fc5e81ebd"
lineNumber: 556
message: "'getUserMedia' called on an object that does not implement interface MediaDevices."
stack: "client.js/Client</Client.prototype.handleTargetAccept@http://localhost:3000/packages/elmarti_video-chat.js?hash=b47cfc90884f41cd3c7e4c69d06caa1fc5e81ebd:556:9\nhandleStream@http://localhost:3000/packages/elmarti_video-chat.js?hash=b47cfc90884f41cd3c7e4c69d06caa1fc5e81ebd:186:21\n_launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:2908:9\n_.forEach@http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149:7\n_launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:2907:41\nsockjs-0.3.4.js/SockJS</REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:142:13\nsockjs-0.3.4.js/SockJS</SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:1309:9\nsockjs-0.3.4.js/SockJS</SockJS.prototype._didMessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:1375:21\nsockjs-0.3.4.js/SockJS</SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:1531:13\n"
__proto__: Object { stack: "", … }
index.js:34:28
error 
TypeError: 'getUserMedia' called on an object that does not implement interface MediaDevices.
Stack trace:
client.js/Client</Client.prototype.handleTargetStream@http://localhost:3000/packages/elmarti_video-chat.js?hash=b47cfc90884f41cd3c7e4c69d06caa1fc5e81ebd:575:13
handleTargetStream@http://localhost:3000/packages/elmarti_video-chat.js?hash=b47cfc90884f41cd3c7e4c69d06caa1fc5e81ebd:218:17
emit/<@http://localhost:3000/packages/rocketchat_streamer.js?hash=2cb2fae7f2524b137f939ca2595b074c2136fc54:62:13
emit@http://localhost:3000/packages/rocketchat_streamer.js?hash=2cb2fae7f2524b137f939ca2595b074c2136fc54:61:5
Streamer/<@http://localhost:3000/packages/rocketchat_streamer.js?hash=2cb2fae7f2524b137f939ca2595b074c2136fc54:265:6
emit/<@http://localhost:3000/packages/rocketchat_streamer.js?hash=2cb2fae7f2524b137f939ca2595b074c2136fc54:62:13
emit@http://localhost:3000/packages/rocketchat_streamer.js?hash=2cb2fae7f2524b137f939ca2595b074c2136fc54:61:5
setupDdpConnection/<@http://localhost:3000/packages/rocketchat_streamer.js?hash=2cb2fae7f2524b137f939ca2595b074c2136fc54:201:6
_launchConnection/self.socket.onmessage/<@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:2908:9
_.forEach@http://localhost:3000/packages/underscore.js?hash=cde485f60699ff9aced3305f70189e39c665183c:149:7
_launchConnection/self.socket.onmessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:2907:41
sockjs-0.3.4.js/SockJS</REventTarget.prototype.dispatchEvent@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:142:13
sockjs-0.3.4.js/SockJS</SockJS.prototype._dispatchMessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:1309:9
sockjs-0.3.4.js/SockJS</SockJS.prototype._didMessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:1375:21
sockjs-0.3.4.js/SockJS</SockJS.websocket/that.ws.onmessage@http://localhost:3000/packages/ddp-client.js?hash=df770fd9a6a02fd730939b97d266ea2b12938e95:1531:13
index.js:34:28

**Comment by elmarti** [comment]
Interesting, looks like the AdapterJS shim isn't working, i'll look into it tomorrow

**Comment by sir007** [comment]
Great !

**Comment by elmarti** [comment]
Fixed as of 2.1.1, due to `getUserMedia` losing its binding

**Comment by sir007** [comment]
It is Ok now.
Thanks elmarti.
I will try to integrate 2.1.1  in my app.
